SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    J.DEPARTMENT_NAME,
    E.SALARY
    
 FROM 
 FITZ.EMPLOYEES E
 JOIN FITZ.DEPARTMENTS J
 ON E.DEPARTMENT_ID = J.DEPARTMENT_ID; 